// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5gYSjJiMIwfNgY2RuLhWFGnygmuDPCPs',
    appId: '1:187468054476:web:c6f0dd2ec8f17167ebe769',
    messagingSenderId: '187468054476',
    projectId: 'to-dolistapp-639d5',
    authDomain: 'to-dolistapp-639d5.firebaseapp.com',
    storageBucket: 'to-dolistapp-639d5.firebasestorage.app',
    measurementId: 'G-B0HMHZ8J79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7uQ5bxYSyY3tfGOsKAhsjG0qm2HPalsc',
    appId: '1:187468054476:android:51d50be1e361f8caebe769',
    messagingSenderId: '187468054476',
    projectId: 'to-dolistapp-639d5',
    storageBucket: 'to-dolistapp-639d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsHfton1AkvX9Dg-gXmyyhv8Jq4T0SvDQ',
    appId: '1:187468054476:ios:b26ea5f298126b6febe769',
    messagingSenderId: '187468054476',
    projectId: 'to-dolistapp-639d5',
    storageBucket: 'to-dolistapp-639d5.firebasestorage.app',
    iosBundleId: 'com.example.toDoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsHfton1AkvX9Dg-gXmyyhv8Jq4T0SvDQ',
    appId: '1:187468054476:ios:b26ea5f298126b6febe769',
    messagingSenderId: '187468054476',
    projectId: 'to-dolistapp-639d5',
    storageBucket: 'to-dolistapp-639d5.firebasestorage.app',
    iosBundleId: 'com.example.toDoListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5gYSjJiMIwfNgY2RuLhWFGnygmuDPCPs',
    appId: '1:187468054476:web:d413cc06db220b83ebe769',
    messagingSenderId: '187468054476',
    projectId: 'to-dolistapp-639d5',
    authDomain: 'to-dolistapp-639d5.firebaseapp.com',
    storageBucket: 'to-dolistapp-639d5.firebasestorage.app',
    measurementId: 'G-QLPDTYVRN5',
  );
}
